export const COLORS = {
  PRIMARY_BACKGROUND: '#000000',
  SECONDARY_BACKGROUND: '#151517',
  TEXT_COLOR: '#FFFFFF',
  COLOR_GREEN: '#198737',
  COLOR_RED: 'red',
  COLOR_GREY: 'grey',
  COLOR_GREY_FOR_NET_WORK: '#6D7885',
  COLOR_BORDER_RADIUS: '#1E1E20',
};
